### ISSUE TITLE
write tests if the structure of JSON send to sorenson is correct

### ISSUE THREAD

**Issue by switowski** [CERNDocumentServer/cds-sorenson#12]
After hours of debugging, I came to a conclusion that it makes sense to write a test that will check if the JSON format of request send to sorenson is correct.
Sorenson won't always return the errors, but can accept the job and get into `Waiting` stage for 1 hour and then fail without any error message.
This was caused, for example, by not putting elements in `SourceMediaList` inside a list.

**Comment by drjova** [comment]
``` python

from jsonschema import validate

schema = {
  "type": "object",
  "properties": {
      "name": {
        "type": "string"
      },
      "movies": {
          "type": "array",
          "items": {
              "type": "object",
              "properties": {
                "title": {
                  "type": "string"
                }
              }
          },
          "minItems": 1,
      }
  },
  "required": ["name", "movies"]
}

data = {
  "name": "Marvel movies"
}

validate(data, schema)
```
