### ISSUE TITLE
api: use default presets

### ISSUE THREAD

**Issue by egabancho** [CERNDocumentServer/cds-sorenson#8]
Currently both `start_encoding` and `batch_start_encoding` take a preset and a list of presets as mandatory parameters.

It would be nice to make this arguments optional and fallback to default values set via config, something like `CDS_SORENSON_DEFAULT_PRESET` and `CDS_SORENSON_DEFAULT_PRESET_SET`

**Comment by switowski** [comment]
I don't think it applies anymore. There will be a list of presets for different aspect ratio and by default, the encoding will be done for all presets for a given aspect ratio.
@egabancho shall we close it ?
